### ISSUE TITLE
How to handle flying directions of UAV

### ISSUE THREAD

**Issue by joshua19881228** [rudrakshkapil/Integrated-RGB-Thermal-Orthomosaicing#2]
It is a meaningful work that a method of alighning IR and RGB images is proposed. As I know,  h20T can not shoot simultaneously among different sensors. IR image is shot about 1 second after Wide Rgb image is shot. In the paper, a batch of image pairs are used to solve the matrix. How do you handle different flying directions？

**Comment by rudrakshkapil** [comment]
Hi @joshua19881228, thanks for the feedback! As for your question about the delay, I'm not sure where you're getting the info that it's about 1 second. It's true that the EXIF headers of the example data (taken by H20T) only provide capture time to the nearest second, but we observed that the delay is much less than that (based on what's captured by the sensors). One suggestion to handle cases if there is a large delay would be to slow down the drone so there isn't much difference in position between the RGB and thermal delay.

**Comment by joshua19881228** [comment]
Thanks. I'll have a test on this subject after.
